import React from 'react';
import {X,ChevronRight,Toilet,Waves,Droplets,Wind,Accessibility,Baby,Gauge} from 'lucide-react';
export const iconFor=t=>({Toilet,Urinal:Waves,Sink:Droplets,Dryer:Wind,Accessible:Accessibility,'Baby Care':Baby}[t]||Gauge);
export function NavItem({icon:Icon,text,active,onClick}){return <button className={'nav-item '+(active?'active':'')} onClick={onClick}><Icon size={17}/><span>{text}</span></button>}
export function PageTitle({eyebrow,title,subtitle,actions}){return <div className="page-title"><div><label>{eyebrow}</label><h1>{title}</h1><p>{subtitle}</p></div>{actions&&<div className="page-title-actions">{actions}</div>}</div>}
export function Modal({title,children,onClose,actions}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X size={18}/></button></div><div className="modal-body">{children}</div>{actions&&<div className="modal-actions">{actions}</div>}</div></div>}
export function MiniTable({rows,columns}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
export function Spark({tone='water'}){return <div className={'spark '+tone}><svg viewBox="0 0 120 42" preserveAspectRatio="none"><path d="M0 28 C15 22,20 16,34 20 S50 37,65 27 S82 8,96 17 S109 31,120 18"/><path d="M0 28 C15 22,20 16,34 20 S50 37,65 27 S82 8,96 17 S109 31,120 18 L120 42 L0 42Z"/></svg></div>}
export function Stat({icon:Icon,label,value,note,tone,change}){return <div className="stat-card interactive-card"><div className={'stat-icon '+tone}><Icon size={20}/></div><div className="stat-copy"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>{change&&<div className="change">↓ {change}</div>}<Spark tone={tone}/></div>}
export function Fixture({f,selected,onClick}){const Icon=iconFor(f.type);return <button title={`${f.id} · ${f.type}`} className={'fixture '+(selected?'selected ':'')+(f.occ?'busy ':'')+(f.status||'normal')} style={{left:f.x+'%',top:f.y+'%'}} onClick={onClick}><span className="sensor"></span><Icon size={28}/><b>{f.id.split('-').pop()}</b></button>}
export function Plan({title,code,items,selected,onSelect}){return <div className="plan-card"><div className="plan-head"><h3>{title} <em>• {code}</em></h3><span>{items.length} fixtures</span></div><div className="plan-image"><img src="/restroom-plan.svg"/>{items.map(f=><Fixture key={f.id} f={f} selected={selected?.id===f.id} onClick={()=>onSelect(f)}/>)}<div className="entrance">›<span>ENTRANCE</span></div></div></div>}
export function TicketForm({fixture,fixtures,onCreated}){const [selectedFixture,setSelectedFixture]=React.useState(fixture?.id||fixtures[0]?.id||'M-W202-T01');const [priority,setPriority]=React.useState('Medium');const [status,setStatus]=React.useState('Open');const [issue,setIssue]=React.useState('Routine maintenance requested from facility twin.');const [saving,setSaving]=React.useState(false);const current=fixtures.find(f=>f.id===selectedFixture)||fixture;const submit=async()=>{setSaving(true);try{const t=await (await import('../services/api')).createTicket({fixtureId:current?.id,priority,status,issue});onCreated?.(t)}finally{setSaving(false)}};return <div className="form-grid"><label className="full">Fixture<select value={selectedFixture} onChange={e=>setSelectedFixture(e.target.value)}>{fixtures.map(f=><option key={f.id}>{f.id} · {f.type} · {f.room}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>Open</option><option>In progress</option><option>Scheduled</option><option>Resolved</option></select></label><label className="full">Issue<textarea value={issue} onChange={e=>setIssue(e.target.value)}/></label><div className="full form-actions"><button className="primary" disabled={saving} onClick={submit}>{saving?'Creating…':'Create ticket'}</button></div></div>}
